# This is a basic workflow to help you get started with Actions

name: TRYOUT DOPA

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: check size
        run: du -sch ./*
      
      - name: tar stuff
        run: tar -czf test.tar.gz ./*

      - name: Display structure of files
        run: ls -R
        working-directory: ./

      - uses: actions/upload-artifact@v2
        with:
          name: my-arf
          path: ./test.tar.gz
          
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Set Test Pass Flag2
        if: success()
        run: |
          echo "WTV=true" >> $GITHUB_ENV
          
      - name: Use the value
        run: |
          echo "${{ env.WTV }}"  
          

      - name: alala
        if: always()
        run: echo still here

      - name: alala
        if: success()
        run: echo still here2
      
      - name: alala
        if: failure()
        run: echo still here3
  
  downloadarf:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ./
        
      - uses: actions/download-artifact@v2
        with:
          name: my-arf
          path: ./
      
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ./

  downloadarf2:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ./
        
      - uses: actions/download-artifact@v2
        with:
          name: my-arf
          path: ./
      
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ./
        
      - name: untar
        run: tar -xzvf test.tar.gz
        working-directory: ./

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ./
        
